version: '3.8'

services:
  mlflow-backend-store:
    image: postgres:14.0
    container_name: mlflow-backend-store 
    volumes:
      - mlflow-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - my_network

  mlflow-artifact-store:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    container_name: mlflow-artifact-store
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ./.env
    command: server /data/minio --console-address :9001
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  mlflow-server:
    image : asia-northeast3-docker.pkg.dev/cheorish/mlops/mlflow:0.0.1
    container_name: mlflow-server
    depends_on:
      - mlflow-backend-store
      - mlflow-artifact-store
    ports:
      - "5001:5000"
    env_file:
      - ./.env
    entrypoint: /usr/src/app/entrypoint.sh
    networks:
      - my_network

volumes:
  mlflow-data:

networks:
  my_network:
    driver: bridge
